#Window & Fonts
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
FONT_SIZE = 50
FONT_TYPE = 'mats bold'
FONT_COLOR = 'darkgoldenrod1'
SCREEN_BORDER_LENGTH = 100

# Environmental Behavior
SCORE_PER_SECOND = 0.1
GAME_SPEED_INCREASE_PER_SECOND = 0.0005
GAME_DIFFICULTY_SPEED_STARTING = 1

# Asteroid Behavior
METEORS_MAX = 7
METEORS_MINIMUM = 5

# Star Behavior
MAX_STARS = 50

# Player Behavior
PLAYER_COLOR_DEFAULT = "white"
PLAYER_COLOR_BOOSTED = "blue"
PLAYER_SIZE_X = 50
PLAYER_SIZE_Y = 60
PLAYER_SPEED_DEFAULT = 300
PLAYER_SPEED_MULTIPLIER_BOOSTED = 3
PLAYER_SPEED_MULTIPLIER_DEFAULT = 1
